name = "bunayya-putra"
compatibility_date = "2025-06-30"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[env.production]
NEXT_PUBLIC_SUPABASE_URL = "https://qzlsccxuokfzwdlqrohx.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bHNjY3h1b2tmendkbHFyb2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2NjI2MDcsImV4cCI6MjA5ODIzODYwN30.CkJ5euA6wQFO0LcQawElxx6haSyA11ARcYjsxPloI7s"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bHNjY3h1b2tmendkbHFyb2h4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MjY2MjYwNywiZXhwIjoyMDk4MjM4NjA3fQ.YJpieTzfT9uhN1Dyd6JXOiqBSXlprIsJNieZmaFHK3g"
R2_ACCOUNT_ID = "5f3c24963db02b0b6a73df072d2675e2"
R2_ACCESS_KEY_ID = "5612ca8b1d07639a96a0b8d49a47349d"
R2_SECRET_ACCESS_KEY = "aaa17675146e84798a748d641e663669a05f762639bce4fe3c90ab563843bdab"
R2_BUCKET = "poster-buku"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://qzlsccxuokfzwdlqrohx.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bHNjY3h1b2tmendkbHFyb2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2NjI2MDcsImV4cCI6MjA5ODIzODYwN30.CkJ5euA6wQFO0LcQawElxx6haSyA11ARcYjsxPloI7s"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bHNjY3h1b2tmendkbHFyb2h4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MjY2MjYwNywiZXhwIjoyMDk4MjM4NjA3fQ.YJpieTzfT9uhN1Dyd6JXOiqBSXlprIsJNieZmaFHK3g"
R2_ACCOUNT_ID = "5f3c24963db02b0b6a73df072d2675e2"
R2_ACCESS_KEY_ID = "5612ca8b1d07639a96a0b8d49a47349d"
R2_SECRET_ACCESS_KEY = "aaa17675146e84798a748d641e663669a05f762639bce4fe3c90ab563843bdab"
R2_BUCKET = "poster-buku"
